namespace: ci-cd
name: jenkins-helm
image: jfrog.it-academy.by/public/jenkins-ci:ibombel
mail: bombel.ilya@gmail.com

service:
 master:
   port: 8080
   targetPort: 8080
 slave:
   port: 50000 
   targetPort: 50000 

requests:
  cpu: 1000m
  memory: 1000Mi
limits:
  cpu: 2300m
  memory: 2300Mi

nfs:
  server: 192.168.37.105
  path: /mnt/IT-Academy/nfs-data/sa2-20-22/ilya_bombel/jenkins

ingress:
  class: nginx
  host: jenkins-helm.k8s-9.sa
  alias: jenkins-helm.k8s-10.sa
  port: 8080
